### ISSUE TITLE
Allow oldest versions for some lib

### ISSUE THREAD

**Issue by emyrtille** [CHStudio/Raven#16]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to install Raven and my others dependency are not compatible

**Describe the solution you'd like**
The library should be compatible with 
`league/openapi-psr7-validator:0.17.0`
`psr/log:^1|^2`

**Describe alternatives you've considered**
Allow `psr/log:^1|^2`

**Additional context**
My project uses `graylog2/gelf-php` which is compatible with `psr/log: ^1|^2`. So, when I want to install Raven with `composer`, it makes errors because Raven needs `psr/log:3`

**Comment by shulard** [comment]
Thank you ! This is fixed in the v0.2.0 ^^
